version: "3.7"
services:
  # MySQL
  mysql:
    image: mysql:latest
    volumes:
      - ./pkg/config/sql:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=douyin
      - MYSQL_USER=cloud
      - MYSQL_PASSWORD=cloud
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"

  # Redis
  redis:
    image: redis:latest
    ports:
      - "16379:6379"


  # ETCD
  Etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib-dev:latest
    command: [ "--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}" ]
    volumes:
      - ./pkg/config/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888"        # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679"       # zpages extension
    depends_on:
      - jaeger-all-in-one

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14268"
      - "14250:14250"
      - "6831:6831"

  # Victoriametrics
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics
    ports:
      - "8428:8428"
      - "8089:8089"
      - "8089:8089/udp"
      - "2003:2003"
      - "2003:2003/udp"
      - "4242:4242"
    command:
      - '--storageDataPath=/storage'
      - '--graphiteListenAddr=:2003'
      - '--opentsdbListenAddr=:4242'
      - '--httpListenAddr=:8428'
      - '--influxListenAddr=:8089'
    restart: always

  # Grafana
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"


  # Pulsar
  pulsar:
    image: apachepulsar/pulsar:latest
    ports:
      - "16650:6650"
      - "18080:8080"
    environment:
      - PULSAR_MEM=${PULSAR_MEM:-"-Xms1g -Xmx1g"}
      - PULSAR_GC=${PULSAR_GC:-"-XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:G1HeapRegionSize=16m -XX:InitiatingHeapOccupancyPercent=35 -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2 -XX:G1HeapWastePercent=10 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=6 -XX:+DisableExplicitGC -XX:+UseStringDeduplication"}
      - PULSAR_LOG_CONF_FILE=/pulsar/conf/log4j2.yaml
      - PULSAR_LOG_DIR=/pulsar/logs
      - PULSAR_CONF=/pulsar/conf
      - PULSAR_EXTRA_CONF=${PULSAR_EXTRA_CONF:-""}
    volumes:
      - ./pulsar/data:/pulsar/data
      - ./pulsar/conf:/pulsar/conf
      - ./pulsar/logs:/pulsar/logs