hertz:
  host: 127.0.0.1
  port: 30000

jwt:
  signingKey: CloudWeDance
  identityKey: id

mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  dbName: douyin
  maxOpenConn: 100
  maxIdleConn: 10

videoRCRedis:
  host: 192.168.197.129
  port: 6379
  password:
  db: 0
  poolSize: 100

commentRCRedis:
  host: 192.168.197.129
  port: 6379
  password:
  db: 1
  poolSize: 100

userRCRedis:
  host: 192.168.197.129
  port: 6379
  password:
  db: 2
  poolSize: 100

messageRCRedis:
  host: 192.168.197.129
  port: 6379
  password:
  db: 3
  poolSize: 100

pulsar:
  url: pulsar://192.168.197.129:6650
  connectionTimeout: 30
  operatorTimeout: 30
